# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-24 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='snoze_user',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snoze_user',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='snoze_user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Snoze_User'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='Accounts.Snoze_User'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Snoze_User'),
        ),
        migrations.AddField(
            model_name='blocked',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='Accounts.Snoze_User'),
        ),
        migrations.AddField(
            model_name='blocked',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Snoze_User'),
        ),
    ]
