# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20181225_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snoze_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
